# Generated by Django 5.0.4 on 2024-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.TextField(default='No description', max_length=200),
        ),
    ]
