# Generated by Django 5.0.4 on 2024-10-06 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprj', '0002_todo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
